steps:
  # Build the frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_API_URL}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/consultantos-frontend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/consultantos-frontend:latest'
      - '-f'
      - 'frontend/Dockerfile'
      - 'frontend'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/consultantos-frontend:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/consultantos-frontend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'consultantos-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/consultantos-frontend:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_API_URL=${_API_URL}'
      - 'PORT=8080'

substitutions:
  _REGION: us-central1
  _API_URL: https://consultantos-api-bdndyf33xa-uc.a.run.app

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

images:
  - 'gcr.io/$PROJECT_ID/consultantos-frontend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/consultantos-frontend:latest'

