"""
Enhanced PDF Generator for Multi-Layered Reports

Generates professional PDFs with:
- Multi-layered structure (Executive, Detailed, Appendices)
- Actionable recommendations with timelines
- Risk/opportunity visualizations
- Enhanced framework analysis
"""
import io
import json
import os
import tempfile
from typing import Optional, Dict, Any
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak,
    Table, TableStyle, Image, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.lib import colors
from datetime import datetime
import plotly.graph_objects as go
import plotly.io as pio
from consultantos.models.enhanced_reports import EnhancedStrategicReport
from consultantos.visualizations import (
    create_porter_radar_figure,
    create_swot_matrix_figure,
    figure_to_json,
    get_cached_figure,
    set_cached_figure,
)
import logging

logger = logging.getLogger(__name__)


def generate_enhanced_pdf_report(
    enhanced_report: EnhancedStrategicReport,
    report_id: Optional[str] = None
) -> bytes:
    """
    Generate enhanced multi-layered PDF report.
    
    Args:
        enhanced_report: Enhanced strategic report
        report_id: Optional report ID for caching
        
    Returns:
        PDF bytes
    """
    # Create temporary PDF file
    with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as tmp:
        pdf_path = tmp.name
    
    try:
        # Create document
        doc = SimpleDocTemplate(
            pdf_path,
            pagesize=A4,
            topMargin=0.75*inch,
            bottomMargin=0.75*inch,
            leftMargin=0.75*inch,
            rightMargin=0.75*inch
        )
        
        # Styles
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#0066cc'),
            spaceAfter=30,
            alignment=TA_CENTER
        )
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#0066cc'),
            spaceAfter=12,
            spaceBefore=12
        )
        subheading_style = ParagraphStyle(
            'CustomSubHeading',
            parent=styles['Heading3'],
            fontSize=14,
            textColor=colors.HexColor('#333333'),
            spaceAfter=8,
            spaceBefore=8
        )
        
        # Build story (content)
        story = []
        
        # Cover Page
        story.append(Spacer(1, 2*inch))
        story.append(Paragraph("ENHANCED STRATEGIC ANALYSIS REPORT", title_style))
        story.append(Spacer(1, 0.5*inch))
        
        company_name = enhanced_report.executive_summary_layer.company_overview.get("name", "Unknown")
        story.append(Paragraph(
            f"<b>{company_name}</b>",
            ParagraphStyle('CompanyName', parent=styles['Normal'], fontSize=18, alignment=TA_CENTER)
        ))
        story.append(Spacer(1, 0.25*inch))
        
        industry = enhanced_report.executive_summary_layer.company_overview.get("industry", "Unknown")
        story.append(Paragraph(
            f"{industry}",
            ParagraphStyle('Industry', parent=styles['Normal'], fontSize=14, alignment=TA_CENTER)
        ))
        story.append(Spacer(1, 2*inch))
        story.append(Paragraph(
            f"Generated by ConsultantOS<br/>{datetime.now().strftime('%B %d, %Y')}",
            ParagraphStyle('Footer', parent=styles['Normal'], fontSize=10, alignment=TA_CENTER, textColor=colors.grey)
        ))
        story.append(PageBreak())
        
        # Table of Contents
        story.append(Paragraph("Table of Contents", heading_style))
        toc_items = [
            "1. Executive Summary",
            "2. Detailed Analysis",
            "3. Actionable Recommendations",
            "4. Risk & Opportunity Assessment",
            "5. Supporting Appendices"
        ]
        for item in toc_items:
            story.append(Paragraph(f"• {item}", styles['Normal']))
            story.append(Spacer(1, 6))
        story.append(PageBreak())
        
        # EXECUTIVE SUMMARY LAYER
        story.append(Paragraph("1. Executive Summary", heading_style))
        
        exec_summary = enhanced_report.executive_summary_layer
        
        # Company Overview
        story.append(Paragraph("<b>Company Overview</b>", subheading_style))
        overview = exec_summary.company_overview
        overview_text = f"""
        <b>Company:</b> {overview.get('name', 'N/A')}<br/>
        <b>Industry:</b> {overview.get('industry', 'N/A')}<br/>
        <b>Description:</b> {overview.get('description', 'N/A')[:200]}...
        """
        story.append(Paragraph(overview_text, styles['Normal']))
        story.append(Spacer(1, 12))
        
        # Key Findings
        story.append(Paragraph("<b>Key Findings</b>", subheading_style))
        for finding in exec_summary.key_findings:
            story.append(Paragraph(f"• {finding}", styles['Normal']))
        story.append(Spacer(1, 12))
        
        # Strategic Recommendations
        story.append(Paragraph("<b>Strategic Recommendations</b>", subheading_style))
        for i, rec in enumerate(exec_summary.strategic_recommendations, 1):
            story.append(Paragraph(f"{i}. {rec}", styles['Normal']))
        story.append(Spacer(1, 12))
        
        # Confidence & Methodology
        confidence_pct = f"{exec_summary.confidence_score * 100:.0f}%"
        story.append(Paragraph(f"<b>Analysis Confidence:</b> {confidence_pct}", styles['Normal']))
        story.append(Paragraph(f"<b>Methodology:</b> {exec_summary.methodology_note}", styles['Normal']))
        story.append(PageBreak())
        
        # DETAILED ANALYSIS LAYER
        story.append(Paragraph("2. Detailed Analysis", heading_style))
        
        detailed = enhanced_report.detailed_analysis_layer
        
        # Framework Breakdowns
        if detailed.framework_breakdowns.get("porter"):
            story.append(Paragraph("<b>Porter's Five Forces - Enhanced Analysis</b>", subheading_style))
            porter_enhanced = detailed.framework_breakdowns["porter"]
            if hasattr(porter_enhanced, 'industry_attractiveness_score'):
                story.append(Paragraph(
                    f"<b>Industry Attractiveness Score:</b> {porter_enhanced.industry_attractiveness_score:.1f}/100",
                    styles['Normal']
                ))
            story.append(Spacer(1, 12))
        
        if detailed.framework_breakdowns.get("swot"):
            story.append(Paragraph("<b>SWOT Analysis - Enhanced</b>", subheading_style))
            swot_enhanced = detailed.framework_breakdowns["swot"]
            if hasattr(swot_enhanced, 'roadmap'):
                story.append(Paragraph("<b>Strategic Roadmap:</b>", styles['Normal']))
                for roadmap_item in swot_enhanced.roadmap[:3]:  # Top 3
                    timeline = roadmap_item.get('timeline', 'N/A')
                    focus = roadmap_item.get('focus', 'N/A')
                    story.append(Paragraph(f"• {timeline}: {focus}", styles['Normal']))
            story.append(Spacer(1, 12))
        
        # Cross-Framework Insights
        if detailed.cross_framework_insights:
            story.append(Paragraph("<b>Cross-Framework Insights</b>", subheading_style))
            for insight in detailed.cross_framework_insights:
                story.append(Paragraph(f"• {insight}", styles['Normal']))
            story.append(Spacer(1, 12))
        
        story.append(PageBreak())
        
        # ACTIONABLE RECOMMENDATIONS
        story.append(Paragraph("3. Actionable Recommendations", heading_style))
        
        recommendations = enhanced_report.actionable_recommendations
        
        # Critical Actions
        if recommendations.critical_actions:
            story.append(Paragraph("<b>Critical Actions (Immediate Priority)</b>", subheading_style))
            for action in recommendations.critical_actions[:5]:  # Top 5
                action_text = f"""
                <b>{action.title}</b><br/>
                Priority: {action.priority.value.upper()} | Timeline: {action.timeline.value.replace('_', '-').title()}<br/>
                Owner: {action.owner or 'Unassigned'}<br/>
                Expected Outcome: {action.expected_outcome}<br/>
                Success Metrics: {', '.join(action.success_metrics[:2])}
                """
                story.append(Paragraph(action_text, styles['Normal']))
                story.append(Spacer(1, 8))
        
        # Grouped by Timeline
        story.append(Paragraph("<b>Recommendations by Timeline</b>", subheading_style))
        
        timeline_groups = [
            ("Immediate (0-3 months)", recommendations.immediate_actions),
            ("Short-term (3-12 months)", recommendations.short_term_actions),
            ("Medium-term (12-24 months)", recommendations.medium_term_actions),
            ("Long-term (24+ months)", recommendations.long_term_actions)
        ]
        
        for timeline_label, actions in timeline_groups:
            if actions:
                story.append(Paragraph(f"<b>{timeline_label}</b>", styles['Normal']))
                for action in actions[:3]:  # Top 3 per timeline
                    story.append(Paragraph(f"• {action.title}", styles['Normal']))
                story.append(Spacer(1, 8))
        
        story.append(PageBreak())
        
        # RISK & OPPORTUNITY ASSESSMENT
        story.append(Paragraph("4. Risk & Opportunity Assessment", heading_style))
        
        risk_opp = enhanced_report.risk_opportunity_matrix
        
        # Top Risks
        if risk_opp.risks:
            story.append(Paragraph("<b>Top Risks</b>", subheading_style))
            risks_table_data = [['Risk', 'Likelihood', 'Impact', 'Risk Score']]
            for risk in risk_opp.risks[:5]:  # Top 5
                risks_table_data.append([
                    risk.title[:40],
                    f"{risk.likelihood:.1f}/10",
                    risk.impact.value,
                    f"{risk.risk_score:.1f}/10"
                ])
            
            risks_table = Table(risks_table_data, colWidths=[3*inch, 1.5*inch, 1*inch, 1*inch])
            risks_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#cc0000')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 11),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige)
            ]))
            story.append(risks_table)
            story.append(Spacer(1, 12))
        
        # Top Opportunities
        if risk_opp.opportunities:
            story.append(Paragraph("<b>Top Opportunities</b>", subheading_style))
            opps_table_data = [['Opportunity', 'Impact', 'Feasibility', 'Priority']]
            for opp in risk_opp.opportunities[:5]:  # Top 5
                opps_table_data.append([
                    opp.title[:40],
                    f"{opp.impact_potential:.1f}/10",
                    f"{opp.feasibility:.1f}/10",
                    f"{opp.priority_score:.1f}/10"
                ])
            
            opps_table = Table(opps_table_data, colWidths=[3*inch, 1.5*inch, 1*inch, 1*inch])
            opps_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#00cc00')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 11),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('BACKGROUND', (0, 1), (-1, -1), colors.lightgreen)
            ]))
            story.append(opps_table)
        
        story.append(PageBreak())
        
        # SUPPORTING APPENDICES
        story.append(Paragraph("5. Supporting Appendices", heading_style))
        
        appendices = enhanced_report.supporting_appendices
        
        # Data Sources
        if appendices.data_sources:
            story.append(Paragraph("<b>Data Sources</b>", subheading_style))
            for source in appendices.data_sources:
                source_text = f"""
                <b>{source.get('type', 'Unknown')}:</b> {source.get('description', 'N/A')}
                """
                story.append(Paragraph(source_text, styles['Normal']))
            story.append(Spacer(1, 12))
        
        # Frameworks Applied
        if appendices.frameworks_applied:
            story.append(Paragraph("<b>Frameworks Applied</b>", subheading_style))
            for framework in appendices.frameworks_applied:
                story.append(Paragraph(f"• {framework}", styles['Normal']))
        
        # Build PDF
        doc.build(story)
        
        # Read bytes
        with open(pdf_path, 'rb') as f:
            pdf_bytes = f.read()
        
        return pdf_bytes
    
    finally:
        # Cleanup
        if os.path.exists(pdf_path):
            os.unlink(pdf_path)

