"""
PDF report generation using ReportLab
"""
import io
import json
import os
import tempfile
from typing import Optional
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak,
    Table, TableStyle, Image
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib import colors
from datetime import datetime
import plotly.graph_objects as go
import plotly.io as pio
from consultantos_core import models as core_models
from consultantos.visualizations import (
    create_porter_radar_figure,
    create_swot_matrix_figure,
    figure_to_json,
    get_cached_figure,
    set_cached_figure,
)


def _load_cached_figure(cache_key: Optional[str]) -> Optional[go.Figure]:
    if not cache_key:
        return None
    cached = get_cached_figure(cache_key)
    if not cached:
        return None
    return pio.from_json(json.dumps(cached))


def _cache_figure(cache_key: Optional[str], figure: go.Figure) -> None:
    if not cache_key:
        return
    set_cached_figure(cache_key, figure_to_json(figure))


def generate_pdf_report(report: core_models.StrategicReport, report_id: Optional[str] = None) -> bytes:
    """Generate professional PDF report using ReportLab"""
    
    # Create temporary PDF file
    with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as tmp:
        pdf_path = tmp.name
    
    try:
        # Create document
        doc = SimpleDocTemplate(
            pdf_path,
            pagesize=A4,
            topMargin=0.75*inch,
            bottomMargin=0.75*inch,
            leftMargin=0.75*inch,
            rightMargin=0.75*inch
        )
        
        # Styles
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#0066cc'),
            spaceAfter=30,
            alignment=TA_CENTER
        )
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#0066cc'),
            spaceAfter=12,
            spaceBefore=12
        )
        
        # Build story (content)
        story = []
        
        # Cover Page
        story.append(Spacer(1, 2*inch))
        story.append(Paragraph("STRATEGIC ANALYSIS REPORT", title_style))
        story.append(Spacer(1, 0.5*inch))
        story.append(Paragraph(
            f"<b>{report.executive_summary.company_name}</b>",
            ParagraphStyle('CompanyName', parent=styles['Normal'], fontSize=18, alignment=TA_CENTER)
        ))
        story.append(Spacer(1, 0.25*inch))
        story.append(Paragraph(
            f"{report.executive_summary.industry}",
            ParagraphStyle('Industry', parent=styles['Normal'], fontSize=14, alignment=TA_CENTER)
        ))
        story.append(Spacer(1, 2*inch))
        story.append(Paragraph(
            f"Generated by ConsultantOS<br/>{datetime.now().strftime('%B %d, %Y')}",
            ParagraphStyle('Footer', parent=styles['Normal'], fontSize=10, alignment=TA_CENTER, textColor=colors.grey)
        ))
        story.append(PageBreak())
        
        # Executive Summary
        story.append(Paragraph("Executive Summary", heading_style))
        story.append(Paragraph("<b>Key Findings:</b>", styles['Normal']))
        story.append(Spacer(1, 6))
        for finding in report.executive_summary.key_findings:
            story.append(Paragraph(f"• {finding}", styles['Normal']))
        story.append(Spacer(1, 12))
        
        story.append(Paragraph("<b>Strategic Recommendation:</b>", styles['Normal']))
        story.append(Paragraph(report.executive_summary.strategic_recommendation, styles['Normal']))
        story.append(Spacer(1, 12))
        
        confidence_pct = f"{report.executive_summary.confidence_score * 100:.0f}%"
        story.append(Paragraph(f"<b>Analysis Confidence:</b> {confidence_pct}", styles['Normal']))
        story.append(PageBreak())
        
        # Porter's 5 Forces
        if report.framework_analysis and report.framework_analysis.porter_five_forces:
            story.append(Paragraph("Porter's Five Forces Analysis", heading_style))
            
            # Try to add chart
            try:
                cache_key = f"porter:{report_id}" if report_id else None
                porter_fig = _load_cached_figure(cache_key)
                if porter_fig is None:
                    porter_fig = create_porter_radar_figure(report.framework_analysis.porter_five_forces)
                    _cache_figure(cache_key, porter_fig)
                img_bytes = pio.to_image(porter_fig, format="png", width=600, height=500)
                img_buffer = io.BytesIO(img_bytes)
                porter_img = Image(img_buffer, width=5*inch, height=4*inch)
                story.append(porter_img)
            except Exception:
                pass  # Skip chart if rendering fails
            
            # Add table
            porter = report.framework_analysis.porter_five_forces
            porter_data = [
                ['Force', 'Score', 'Assessment'],
                ['Supplier Power', f"{porter.supplier_power}/5", ''],
                ['Buyer Power', f"{porter.buyer_power}/5", ''],
                ['Competitive Rivalry', f"{porter.competitive_rivalry}/5", ''],
                ['Threat of Substitutes', f"{porter.threat_of_substitutes}/5", ''],
                ['Threat of New Entrants', f"{porter.threat_of_new_entrants}/5", '']
            ]
            
            porter_table = Table(porter_data, colWidths=[2.5*inch, 1*inch, 3*inch])
            porter_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0066cc')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 12),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            
            story.append(porter_table)
            story.append(Spacer(1, 12))
            story.append(Paragraph(
                f"<b>Overall Competitive Intensity:</b> {porter.overall_intensity}",
                styles['Normal']
            ))
            story.append(PageBreak())
        
        # SWOT Analysis
        if report.framework_analysis and report.framework_analysis.swot_analysis:
            story.append(Paragraph("SWOT Analysis", heading_style))
            
            swot = report.framework_analysis.swot_analysis
            swot_data = [
                ['Strengths', 'Weaknesses'],
                [
                    '<br/>'.join(['• ' + s for s in swot.strengths]),
                    '<br/>'.join(['• ' + w for w in swot.weaknesses])
                ],
                ['Opportunities', 'Threats'],
                [
                    '<br/>'.join(['• ' + o for o in swot.opportunities]),
                    '<br/>'.join(['• ' + t for t in swot.threats])
                ]
            ]
            
            swot_table = Table(swot_data, colWidths=[3.25*inch, 3.25*inch])
            swot_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.green),
                ('BACKGROUND', (0, 2), (-1, 2), colors.lightblue),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('TEXTCOLOR', (0, 2), (-1, 2), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTNAME', (0, 2), (-1, 2), 'Helvetica-Bold'),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            
            story.append(swot_table)
            story.append(PageBreak())
        
        # Recommendations
        story.append(Paragraph("Strategic Recommendations", heading_style))
        for i, rec in enumerate(report.recommendations, 1):
            story.append(Paragraph(f"<b>{i}.</b> {rec}", styles['Normal']))
            story.append(Spacer(1, 8))
        
        # Build PDF
        doc.build(story)
        
        # Read bytes
        with open(pdf_path, 'rb') as f:
            pdf_bytes = f.read()
        
        return pdf_bytes
    
    finally:
        # Cleanup
        if os.path.exists(pdf_path):
            os.unlink(pdf_path)
